AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: LambdaJfrDemo

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      MemorySize: 512
      Handler: com.airties.demo.Lambda::handleRequest
      CodeUri: build/distributions/lambda.zip
      Timeout: 30
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
      - Statement:
        - Effect: Allow
          Action: s3:ListAllMyBuckets
          Resource: '*'
        - Effect: Allow
          Action: s3:PutObject
          Resource: 'arn:aws:s3:::devoxx-demo/jfr-dumps/*'
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: "-XX:FlightRecorderOptions=stackdepth=128 -XX:StartFlightRecording=maxsize=50M,settings=profile -javaagent:/opt/jfr-layer/layer-all.jar"
          JFR_DUMP_PATH: "s3://devoxx-demo/jfr-dumps/"
      Layers:
        - Ref: Layer

  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../layer/build/distributions/layer.zip
      CompatibleRuntimes:
        - java11

Outputs:
  LambdaUrlEndpoint:
      Description: "URL Endpoint"
      Value:
        Fn::GetAtt: LambdaUrl.FunctionUrl